//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HoSoSucKhoeCaNhan_FullEntities : DbContext
    {
        public HoSoSucKhoeCaNhan_FullEntities()
            : base("name=HoSoSucKhoeCaNhan_FullEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiSoKham> ChiSoKham { get; set; }
        public DbSet<DiUng> DiUng { get; set; }
        public DbSet<DonThuoc> DonThuoc { get; set; }
        public DbSet<HoSoNguoiDung> HoSoNguoiDung { get; set; }
        public DbSet<LanKham> LanKham { get; set; }
        public DbSet<LichSuPhauThuat> LichSuPhauThuat { get; set; }
        public DbSet<LichSuTiemChung> LichSuTiemChung { get; set; }
        public DbSet<NhatKySucKhoe> NhatKySucKhoe { get; set; }
        public DbSet<TaiKhoan> TaiKhoan { get; set; }
        public DbSet<TaiLieuKham> TaiLieuKham { get; set; }
        public DbSet<TienSuBenh> TienSuBenh { get; set; }
        public DbSet<TienSuGiaDinh> TienSuGiaDinh { get; set; }
        public DbSet<TheBaoHiem> TheBaoHiem { get; set; }
        public DbSet<VaiTro> VaiTro { get; set; }
        public DbSet<View_BieuDoSucKhoe> View_BieuDoSucKhoe { get; set; }
        public DbSet<View_CanhBaoSucKhoe> View_CanhBaoSucKhoe { get; set; }
        public DbSet<View_LichSuDungThuoc> View_LichSuDungThuoc { get; set; }
        public DbSet<View_TongHopLichSuKham> View_TongHopLichSuKham { get; set; }
        public DbSet<DanhMucThuoc> DanhMucThuoc { get; set; }
    
        public virtual int Proc_CapNhatChiSoSinhTon(Nullable<int> maLanKham, Nullable<int> huyetApTamThu, Nullable<int> huyetApTamTruong, Nullable<int> nhipTim, Nullable<decimal> nhietDo, Nullable<decimal> canNang)
        {
            var maLanKhamParameter = maLanKham.HasValue ?
                new ObjectParameter("MaLanKham", maLanKham) :
                new ObjectParameter("MaLanKham", typeof(int));
    
            var huyetApTamThuParameter = huyetApTamThu.HasValue ?
                new ObjectParameter("HuyetApTamThu", huyetApTamThu) :
                new ObjectParameter("HuyetApTamThu", typeof(int));
    
            var huyetApTamTruongParameter = huyetApTamTruong.HasValue ?
                new ObjectParameter("HuyetApTamTruong", huyetApTamTruong) :
                new ObjectParameter("HuyetApTamTruong", typeof(int));
    
            var nhipTimParameter = nhipTim.HasValue ?
                new ObjectParameter("NhipTim", nhipTim) :
                new ObjectParameter("NhipTim", typeof(int));
    
            var nhietDoParameter = nhietDo.HasValue ?
                new ObjectParameter("NhietDo", nhietDo) :
                new ObjectParameter("NhietDo", typeof(decimal));
    
            var canNangParameter = canNang.HasValue ?
                new ObjectParameter("CanNang", canNang) :
                new ObjectParameter("CanNang", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_CapNhatChiSoSinhTon", maLanKhamParameter, huyetApTamThuParameter, huyetApTamTruongParameter, nhipTimParameter, nhietDoParameter, canNangParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_DangKyTaiKhoan(string tenDangNhap, string matKhauHash, string email, string hoTen)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauHashParameter = matKhauHash != null ?
                new ObjectParameter("MatKhauHash", matKhauHash) :
                new ObjectParameter("MatKhauHash", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_DangKyTaiKhoan", tenDangNhapParameter, matKhauHashParameter, emailParameter, hoTenParameter);
        }
    
        public virtual ObjectResult<Proc_LayChiTietLanKham_Result> Proc_LayChiTietLanKham(Nullable<int> maLanKham)
        {
            var maLanKhamParameter = maLanKham.HasValue ?
                new ObjectParameter("MaLanKham", maLanKham) :
                new ObjectParameter("MaLanKham", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_LayChiTietLanKham_Result>("Proc_LayChiTietLanKham", maLanKhamParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Proc_ThemMoiLanKham(Nullable<int> maHoSo, Nullable<System.DateTime> ngayKham, string noiKham, string khoaKham, string bacSiKham, string lyDoKham, string chanDoan, string loiDan, Nullable<System.DateTime> ngayTaiKham)
        {
            var maHoSoParameter = maHoSo.HasValue ?
                new ObjectParameter("MaHoSo", maHoSo) :
                new ObjectParameter("MaHoSo", typeof(int));
    
            var ngayKhamParameter = ngayKham.HasValue ?
                new ObjectParameter("NgayKham", ngayKham) :
                new ObjectParameter("NgayKham", typeof(System.DateTime));
    
            var noiKhamParameter = noiKham != null ?
                new ObjectParameter("NoiKham", noiKham) :
                new ObjectParameter("NoiKham", typeof(string));
    
            var khoaKhamParameter = khoaKham != null ?
                new ObjectParameter("KhoaKham", khoaKham) :
                new ObjectParameter("KhoaKham", typeof(string));
    
            var bacSiKhamParameter = bacSiKham != null ?
                new ObjectParameter("BacSiKham", bacSiKham) :
                new ObjectParameter("BacSiKham", typeof(string));
    
            var lyDoKhamParameter = lyDoKham != null ?
                new ObjectParameter("LyDoKham", lyDoKham) :
                new ObjectParameter("LyDoKham", typeof(string));
    
            var chanDoanParameter = chanDoan != null ?
                new ObjectParameter("ChanDoan", chanDoan) :
                new ObjectParameter("ChanDoan", typeof(string));
    
            var loiDanParameter = loiDan != null ?
                new ObjectParameter("LoiDan", loiDan) :
                new ObjectParameter("LoiDan", typeof(string));
    
            var ngayTaiKhamParameter = ngayTaiKham.HasValue ?
                new ObjectParameter("NgayTaiKham", ngayTaiKham) :
                new ObjectParameter("NgayTaiKham", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Proc_ThemMoiLanKham", maHoSoParameter, ngayKhamParameter, noiKhamParameter, khoaKhamParameter, bacSiKhamParameter, lyDoKhamParameter, chanDoanParameter, loiDanParameter, ngayTaiKhamParameter);
        }
    
        public virtual int Proc_KeDonThuoc(Nullable<int> maLanKham, string tenThuoc, string hamLuong, Nullable<int> soLuong, string donViTinh, string cachDung, string ghiChu)
        {
            var maLanKhamParameter = maLanKham.HasValue ?
                new ObjectParameter("MaLanKham", maLanKham) :
                new ObjectParameter("MaLanKham", typeof(int));
    
            var tenThuocParameter = tenThuoc != null ?
                new ObjectParameter("TenThuoc", tenThuoc) :
                new ObjectParameter("TenThuoc", typeof(string));
    
            var hamLuongParameter = hamLuong != null ?
                new ObjectParameter("HamLuong", hamLuong) :
                new ObjectParameter("HamLuong", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var cachDungParameter = cachDung != null ?
                new ObjectParameter("CachDung", cachDung) :
                new ObjectParameter("CachDung", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_KeDonThuoc", maLanKhamParameter, tenThuocParameter, hamLuongParameter, soLuongParameter, donViTinhParameter, cachDungParameter, ghiChuParameter);
        }
    }
}
