//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiUng
    {
        public int MaDiUng { get; set; }
        public Nullable<int> MaHoSo { get; set; }
        public string TacNhan { get; set; }
        public string MucDo { get; set; }
        public string BieuHien { get; set; }
        public Nullable<System.DateTime> NgayPhatHien { get; set; }
    
        public virtual HoSoNguoiDung HoSoNguoiDung { get; set; }
    }
}
