//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonThuoc
    {
        public int MaDonThuoc { get; set; }
        public Nullable<int> MaLanKham { get; set; }
        public string TenThuoc { get; set; }
        public string HamLuong { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DonViTinh { get; set; }
        public string CachDung { get; set; }
        public string GhiChu { get; set; }
    
        public virtual LanKham LanKham { get; set; }
    }
}
