//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoNguoiDung
    {
        public HoSoNguoiDung()
        {
            this.DiUng = new HashSet<DiUng>();
            this.LanKham = new HashSet<LanKham>();
            this.LichSuPhauThuat = new HashSet<LichSuPhauThuat>();
            this.LichSuTiemChung = new HashSet<LichSuTiemChung>();
            this.NhatKySucKhoe = new HashSet<NhatKySucKhoe>();
            this.TienSuBenh = new HashSet<TienSuBenh>();
            this.TienSuGiaDinh = new HashSet<TienSuGiaDinh>();
            this.TheBaoHiem = new HashSet<TheBaoHiem>();
        }
    
        public int MaHoSo { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string NhomMau { get; set; }
        public Nullable<decimal> ChieuCaoCoDinh { get; set; }
        public Nullable<decimal> CanNangHienTai { get; set; }
        public string SoDienThoaiLienHe { get; set; }
    
        public virtual ICollection<DiUng> DiUng { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual ICollection<LanKham> LanKham { get; set; }
        public virtual ICollection<LichSuPhauThuat> LichSuPhauThuat { get; set; }
        public virtual ICollection<LichSuTiemChung> LichSuTiemChung { get; set; }
        public virtual ICollection<NhatKySucKhoe> NhatKySucKhoe { get; set; }
        public virtual ICollection<TienSuBenh> TienSuBenh { get; set; }
        public virtual ICollection<TienSuGiaDinh> TienSuGiaDinh { get; set; }
        public virtual ICollection<TheBaoHiem> TheBaoHiem { get; set; }
    }
}
