//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanKham
    {
        public LanKham()
        {
            this.ChiSoKham = new HashSet<ChiSoKham>();
            this.DonThuoc = new HashSet<DonThuoc>();
            this.TaiLieuKham = new HashSet<TaiLieuKham>();
        }
    
        public int MaLanKham { get; set; }
        public Nullable<int> MaHoSo { get; set; }
        public System.DateTime NgayKham { get; set; }
        public string NoiKham { get; set; }
        public string KhoaKham { get; set; }
        public string BacSiKham { get; set; }
        public string LyDoKham { get; set; }
        public string ChanDoanChinh { get; set; }
        public string LoiDanBacSi { get; set; }
        public Nullable<System.DateTime> NgayTaiKham { get; set; }
    
        public virtual ICollection<ChiSoKham> ChiSoKham { get; set; }
        public virtual ICollection<DonThuoc> DonThuoc { get; set; }
        public virtual HoSoNguoiDung HoSoNguoiDung { get; set; }
        public virtual ICollection<TaiLieuKham> TaiLieuKham { get; set; }
    }
}
