//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuTiemChung
    {
        public int MaTiemChung { get; set; }
        public Nullable<int> MaHoSo { get; set; }
        public string TenVacXin { get; set; }
        public Nullable<System.DateTime> NgayTiem { get; set; }
        public Nullable<int> MuiSo { get; set; }
        public string DiaDiemTiem { get; set; }
        public string PhanUngSauTiem { get; set; }
        public Nullable<System.DateTime> NgayHenMuiTiepTheo { get; set; }
    
        public virtual HoSoNguoiDung HoSoNguoiDung { get; set; }
    }
}
