//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuPhauThuat
    {
        public int MaPhauThuat { get; set; }
        public Nullable<int> MaHoSo { get; set; }
        public string TenPhauThuat { get; set; }
        public Nullable<System.DateTime> NgayThucHien { get; set; }
        public string NoiThucHien { get; set; }
        public string BacSiPhauThuat { get; set; }
        public string GhiChuHauPhau { get; set; }
    
        public virtual HoSoNguoiDung HoSoNguoiDung { get; set; }
    }
}
