//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.HoSoNguoiDung = new HashSet<HoSoNguoiDung>();
        }
    
        public int MaTaiKhoan { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhauHash { get; set; }
        public string Email { get; set; }
        public Nullable<int> MaVaiTro { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual ICollection<HoSoNguoiDung> HoSoNguoiDung { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
