//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieuKham
    {
        public int MaTaiLieu { get; set; }
        public Nullable<int> MaLanKham { get; set; }
        public string TenTaiLieu { get; set; }
        public string LoaiFile { get; set; }
        public string DuongDanFile { get; set; }
        public Nullable<System.DateTime> NgayUpload { get; set; }
    
        public virtual LanKham LanKham { get; set; }
    }
}
