//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheBaoHiem
    {
        public int MaThe { get; set; }
        public Nullable<int> MaHoSo { get; set; }
        public string SoThe { get; set; }
        public string LoaiBaoHiem { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string NoiDangKyKhamBanDau { get; set; }
        public string AnhChupThe { get; set; }
    
        public virtual HoSoNguoiDung HoSoNguoiDung { get; set; }
    }
}
