//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TienSuBenh
    {
        public int MaTienSu { get; set; }
        public Nullable<int> MaHoSo { get; set; }
        public string TenBenh { get; set; }
        public Nullable<int> NamPhatHien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> DangDieuTri { get; set; }
    
        public virtual HoSoNguoiDung HoSoNguoiDung { get; set; }
    }
}
