//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CanhBaoSucKhoe
    {
        public System.DateTime NgayKham { get; set; }
        public string HoTen { get; set; }
        public string NoiKham { get; set; }
        public Nullable<int> HuyetApTamThu { get; set; }
        public Nullable<decimal> NhietDo { get; set; }
        public string CanhBao { get; set; }
    }
}
