//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BieuDoSucKhoe
    {
        public int MaHoSo { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgayKham { get; set; }
        public Nullable<int> HuyetApTamThu { get; set; }
        public Nullable<int> HuyetApTamTruong { get; set; }
        public Nullable<int> NhipTim { get; set; }
        public Nullable<decimal> CanNang { get; set; }
        public Nullable<decimal> DuongHuyet { get; set; }
    }
}
