//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoSoBenhAnDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TongHopLichSuKham
    {
        public int MaLanKham { get; set; }
        public int MaHoSo { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgayKham { get; set; }
        public string NoiKham { get; set; }
        public string ChanDoanChinh { get; set; }
        public Nullable<System.DateTime> NgayTaiKham { get; set; }
        public string TrangThai { get; set; }
    }
}
